server:
  port: 8081
  
mybatis: 
  mapper-locations: "classpath:mapper/*.xml"
  #config-location: "classpath:mybatis/mybatis.cfg.xml"        # mybatis配置文件所在路径
  #mapper-locations: "classpath:mybatis/mapper/**/*.xml"       # mapper映射文件
  #type-aliases-package: springbootjsp.zzq.controller.entity             # 别名类所在包
spring:
  application: 
    name: springbootjsp                                             #微服务的名字
  datasource: 
    driver-class-name: com.mysql.cj.jdbc.Driver                # mysql驱动包
    url: jdbc:mysql://localhost:3306/home?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false&rewriteBatchedStatements=true                   # 数据库名称
    username: root                                             # 数据库用户名
    password: 123456                                           # 密码
  mvc:
    view:
      prefix: /WEB-INF/jsp/                                   # 视图解析前缀
      suffix: .jsp                                            # 视图解析后缀

